# Generated by Django 4.0.2 on 2022-03-18 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasygolf', '0002_article_athlete_event_player_delete_choice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='events_played_in',
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(default=1987, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
