# Generated by Django 4.0.3 on 2022-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywordsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchbar', models.TextField(verbose_name=30)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.TextField(max_length=15)),
                ('modelname', models.TextField(max_length=15)),
                ('year', models.TextField(max_length=5)),
            ],
        ),
    ]
