# Generated by Django 4.0.1 on 2022-01-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todoitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('created_date', models.DateField()),
                ('completed_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
